# These database containers are ONLY meant for development!
# Please properly configure a production database
version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rustyfusion
    container_name: rf-db-postgres

