name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build base
      run: cargo build --verbose --no-default-features
    - name: Build with PostgreSQL
      run: cargo build --verbose --no-default-features --features postgres
    - name: Build with MongoDB
      run: cargo build --verbose --no-default-features --features mongo
    - name: Run tests
      run: cargo test --verbose
    - name: Check linter
      run: cargo clippy -- -Dwarnings
    - name: Check formatting
      run: cargo fmt --check
